# -*- coding: utf-8 -*-
"""Predictive Analytics - Heart Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8IE4sBosDh1sFPdpKkN5BVuOK4AwMBz

#**Heart Disease Classification**

## Import Library
Load library yang dibutuhkan
"""

import pandas as pd
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

"""Karena data dari kaggle hub, maka perlu didownload dulu"""

path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction")
print("Path to dataset files:", path)

"""Melakukan load data dari dataset 'heart.csv' dan memastikan termuat dengan benar"""

df = pd.read_csv(path + '/heart.csv')
df.head()

"""Menampilkan informasi tentang dataset yang dimuat"""

df.info()

"""Mencari informasi tentang sebaran data setiap kolomnya"""

df.describe(include='all')

"""## **Exploratory Data Analysis (EDA)**

memisahkan fitur numerik dan kategorikal
"""

sns.set_theme(style='whitegrid')
numerical_cols = ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']
categorical_cols = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

"""Univariate Analysis fitur numerik"""

plt.figure(figsize=(15, 8))
for i, col in enumerate(numerical_cols, 1):
  plt.subplot(2, 3, i)
  sns.histplot(df[col], kde=True, color='royalblue')
  plt.title(f'Distribusi {col}')
plt.tight_layout()
plt.show()

"""Univariate analysis untuk fitur kategorik"""

plt.figure(figsize=(16,10))
for i, col in enumerate(categorical_cols, 1):
  plt.subplot(3,3,i)
  sns.countplot(data=df, x=col, hue=col, palette='Set2', legend=False)
  plt.title(f'Countplot {col}')
plt.tight_layout()
plt.show()

"""Multivariate analysis fitur kategorikal utama dengan Target HeartDisease"""

plt.figure(figsize=(15,5))
for i, col in enumerate(['ChestPainType', 'ExerciseAngina', 'ST_Slope'], 1):
  plt.subplot(1,3,i)
  sns.countplot(data=df, x=col, hue='HeartDisease', palette='coolwarm')
  plt.title(f'{col} vs HeartDisease')
plt.tight_layout()
plt.show()

"""heatmap korelasi numerik dengan fitur target"""

plt.figure(figsize=(8,6))
sns.heatmap(df[numerical_cols + ['HeartDisease']].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Matriks Korelasi Numerik dengan HeartDisease')
plt.show()

"""## **Data Preparation**

salin dataframe untuk preprocessing
"""

df_clean = df.copy()

"""imputasi feature restingBP karena tidak make sense tekanan darah nilainya 0. Diganti dengan median"""

median_bp = df_clean[df_clean['RestingBP'] > 0]['RestingBP'].median()
df_clean['RestingBP'] = df_clean['RestingBP'].replace(0, median_bp)

"""imputasi nilai feature Cholesterol = 0 dengan median"""

median_chol = df_clean[df_clean['Cholesterol'] > 0]['Cholesterol'].median()
df_clean['Cholesterol'] = df_clean['Cholesterol'].replace(0, median_chol)

"""Encoding fitur kategorikal menggunakan One-Hot Encoding"""

df_encoded = pd.get_dummies(df_clean, columns=categorical_cols, drop_first=True)

"""memisahkan fitur dengan Target"""

X = df_encoded.drop('HeartDisease', axis=1)
y = df_encoded['HeartDisease']

"""train test split dengan 80% train dan 20% test"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

"""feature scaling pada fitur numerik (kecuali FastingBS)"""

nums_cols_to_scale = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
scaler = StandardScaler()
X_train[nums_cols_to_scale] = scaler.fit_transform(X_train[nums_cols_to_scale])
X_test[nums_cols_to_scale] = scaler.transform(X_test[nums_cols_to_scale])

"""verifikasi bentuk data"""

print(f"Jumlah sampel Train: {X_train.shape[0]}, Dimensi Fitur: {X_train.shape[1]}")
print(f"Jumlah sampel Test: {X_test.shape[0]}, Dimensi Fitur: {X_test.shape[1]}")
X_train.head()

"""## **Modeling**

tahap ini akan dilakukan modeling dengan 3 algoritma berbeda dan hyper parameter dengan metode Grid Search. Berikut algoritma yang dipakai:
*  K-Nearest Neighbors (KNN)
*  Random Forest Classifier
*  XGBoost Classifier

import library yang diperlukan
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score

"""inisialisasi model"""

knn = KNeighborsClassifier(n_neighbors=5)
rf = RandomForestClassifier(random_state=42)
xgb = XGBClassifier(random_state=42, eval_metric='logloss')

"""training baseline (tanpa hyperparameter tuning)"""

knn.fit(X_train, y_train)
rf.fit(X_train, y_train)
xgb.fit(X_train, y_train)

"""HyperParameter Tuning pada model Random Forest"""

param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [4, 6, 8, 10],
    'min_samples_split': [2, 5, 10]
}

grid_rf = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                       param_grid=param_grid_rf,
                       cv=5,
                       scoring='f1',
                       n_jobs=-1)
grid_rf.fit(X_train, y_train)
best_rf = grid_rf.best_estimator_

print('Parameter Terbaik Random Forest:', grid_rf.best_params_)

"""## **Evaluasi**"""

models = {
    'KNN': knn,
    'Random Forest': rf,
    'XGBoost': xgb,
    'Best Random Forest': best_rf
}
metrics_list = []

"""prediksi data uji dengan model yang sudah dilatih dan hitung metriknya"""

for name, model in models.items():
  y_pred = model.predict(X_test)
  y_pred_proba = model.predict_proba(X_test)[:, 1] if hasattr(model, 'predict_proba') else None

  acc = accuracy_score(y_test, y_pred)
  prec = precision_score(y_test,y_pred)
  rec = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  auc = roc_auc_score(y_test, y_pred_proba) if y_pred_proba is not None else np.nan

  metrics_list.append({
      'Model': name,
      'Accuracy': acc,
      'Precision': prec,
      'Recall': rec,
      'F1-Score': f1,
      'ROC-AUC': auc
  })

"""masukkan ke dataframe untuk perbandingan"""

df_metrics = pd.DataFrame(metrics_list)
metrics_cols = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
print("=== Tabel Perbandingan Kinerja Model pada Data Uji ===")
display(df_metrics.style.highlight_max(color='lightgreen', axis=0, subset=metrics_cols))

"""visualisasi confusion matrix untuk model terbaik, yaitu Random Forest tanpa hyperparameter tuning"""

y_pred_rf = rf.predict(X_test)
cm_rf = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(6,5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal (0)', 'Heart Disease (1)'],
            yticklabels=['Normal (0)', 'Heart Disease (1)'])
plt.title('Confusion Matrix - Random Forest')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.show()

print("\nClassification Report (Random Forest):\n")
print(classification_report(y_test, y_pred_rf, target_names=['Normal (0)', 'Heart Disease (1)']))